name: Core Library
owned_globs:
  # First list specific files this team is responsible for
  - lib/feature_map.rb
  - lib/feature_map/cli.rb
  - lib/feature_map/configuration.rb
  - lib/feature_map/constants.rb
  - lib/feature_map/mapper.rb
  - lib/feature_map/commit.rb
  - lib/feature_map/validator.rb
  - lib/feature_map/output_color.rb
  - lib/feature_map/code_features.rb
  - lib/feature_map/code_features/**/*
  - spec/lib/feature_map_spec.rb
  - spec/lib/feature_map/commit_spec.rb
  - spec/lib/feature_map/code_features_spec.rb
  - spec/lib/feature_map/code_features/**/*
  - spec/lib/feature_map/cli_spec.rb
  - spec/spec_helper.rb
  # Catch-all pattern to own any files not owned by other teams
  - "**/*"
